encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("new", views.display_new_entry_form, name="display_new_entry_form"),
    path("new/create", views.create_new_entry, name="create_new_entry"),
    path("random", views.random_entry, name="random_entry"),
    path("<str:entry_name>/edit_entry", views.edit_entry, name="edit_entry"),
    path("<str:entry_name>/edit", views.edit_display, name="edit_display"),
    path("<str:entry_name>", views.entry_page, name="entry_page")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
import random
import markdown2

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry_page(request, entry_name):
    if util.get_entry(entry_name) is not None:
        html_entry = markdown2.markdown(util.get_entry(entry_name))
        return render(request, "encyclopedia/entry_content.html", {
            "entry": html_entry,
            "entry_name": entry_name
        })
    
    else:
        return render(request, "encyclopedia/error_page.html")
    
def search(request):
    
    # Capture user query
    if request.method == "GET":
        query = request.GET.get('q', '')
        
        # Exact query match
        entry_match_list = [entry for entry in util.list_entries() if query.lower() == entry.lower()]
        entry_match_string = "".join(entry_match_list)
        
        # Substring match
        substring_list = [entry for entry in util.list_entries() if query.lower() in entry.lower()]
        
        # Execute statement if there is an exact match
        if len(entry_match_list) == 1:
            html_entry = markdown2.markdown(util.get_entry(entry_match_string))
            return render(request, "encyclopedia/entry_content.html", {
            "entry": html_entry,
            "entry_name": entry_match_string
        })
        
        # Execute statement if there is a substring match
        elif len(substring_list) > 0:
            return render(request, "encyclopedia/search.html", {
                "search_result": substring_list,
                "query": query
            })
            
        # No results found
        else:
            return render(request, "encyclopedia/no_result.html")
        
def display_new_entry_form(request):
            return render(request, "encyclopedia/create_new.html")
        
def create_new_entry(request):
    
    if request.method == "POST":
        title = request.POST["entry_title"]
        content = request.POST["entry_content"]
        
        try:
            if util.check_entry(title):
                util.save_entry(title, content)
                return HttpResponseRedirect(reverse("encyclopedia:entry_page", args=(title,)))
        
            else:
                return render(request, "encyclopedia/already_exist.html")
            
        except:
            return render(request, "encyclopedia/invalid_entry.html")
        
def edit_display(request, entry_name):
     if util.get_entry(entry_name) is not None:
        return render(request, "encyclopedia/edit_entry.html", {
            "entry": util.get_entry(entry_name),
            "entry_name": entry_name
        })
    
     else:
        return render(request, "encyclopedia/error_page.html")
    
def edit_entry(request, entry_name):
    
    if request.method == "POST":
        content = request.POST["entry_content"]
        util.save_entry_old(entry_name, content)
        return HttpResponseRedirect(reverse("encyclopedia:entry_page", args=(entry_name,)))
    
def random_entry(request):
    randomized_list = random.sample(util.list_entries(), len(util.list_entries()))
    html_entry = markdown2.markdown(util.get_entry(randomized_list[0]))
    return render(request, "encyclopedia/entry_content.html", {
        "entry": html_entry,
        "entry_name": randomized_list[0]
    })

encyclopedia/templates/encyclopedia/already_exist.html
{% extends "encyclopedia/layout.html" %}

    {% block title %}
        Encyclopedia
    {% endblock %}

    {% block body %}
        <p>Entry already exists</p>
    {% endblock %}

encyclopedia/templates/encyclopedia/create_new.html
{% extends "encyclopedia/layout.html" %}

{% load static %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block head %}
<link href="{% static 'encyclopedia/create_new_styles.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}
<p>Create new entry</p>

<div class="form_container">
    <form action="{% url 'encyclopedia:create_new_entry' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Entry title</label>
            <input name="entry_title" type="text" class="form-control" id="exampleFormControlInput1">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Content</label>
            <textarea name="entry_content" style="height: 300px" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>

        <button type="submit" class="btn btn-dark">Save</button>
        <a href="{% url 'encyclopedia:index' %}" type="button" class="btn btn-dark">Cancel</a>
    </form>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/edit_entry.html
{% extends "encyclopedia/layout.html" %}

{% load static %}

{% block title %}
{{ entry_name }}
{% endblock %}

{% block head %}
<link href="{% static 'encyclopedia/edit_styles.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}
<p>Editting content of {{ entry_name }}</p>

<div class="form_container">
    <form action="{% url 'encyclopedia:edit_entry' entry_name %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="myinput" class="form-label">Entry title</label>
            <input name="entry_title" type="text" class="form-control" id="myinput" value="{{ entry_name }}" disabled>
        </div>
        <div class="mb-3">
            <label for="mytextarea" class="form-label">Content</label>
            <textarea name="entry_content" class="form-control" id="mytextarea" rows="6">{{ entry }}</textarea>
        </div>

        <button type="submit" class="btn btn-dark">Save</button>
        <a href="{% url 'encyclopedia:index' %}" type="button" class="btn btn-dark">Cancel</a>
    </form>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/entry_content.html
{% extends "encyclopedia/layout.html" %}

{% load static %}

{% block title %}
{{ entry_name }}
{% endblock %}

{% block head %}
<link href="{% static 'encyclopedia/entry_content_styles.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}
<div class="button_container">
    <a href="{% url 'encyclopedia:edit_display' entry_name %}" type="button" class="btn btn-dark">Edit</a>
</div>

<div>
    <p>{{ entry|safe }}</p>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/error_page.html
{% extends "encyclopedia/layout.html" %}

    {% block title %}
        Encyclopedia
    {% endblock %}

    {% block body %}
        <p>Page not found</p>
    {% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry_page' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/invalid_entry.html
{% extends "encyclopedia/layout.html" %}

    {% block title %}
        Encyclopedia
    {% endblock %}

    {% block body %}
        <p>Entry is invalid, please <a href="{% url 'encyclopedia:display_new_entry_form' %}">try again</a></p>
    {% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        {% block head %}{% endblock %}
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form name="search_form" id="" action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:display_new_entry_form' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_entry' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/no_result.html
{% extends "encyclopedia/layout.html" %}

    {% block title %}
        Encyclopedia
    {% endblock %}

    {% block body %}
        <p>No entry matches your query</p>
    {% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<h2>Search result for "{{ query }}"</h2>

<ul>
    {% for entry in search_result %}
    <li><a href="{% url 'encyclopedia:entry_page' entry %}">{{ entry }}</a></li>
    {% endfor %}
</ul>

{% endblock %}